[project]
name = "hmm-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "daft>=0.5.9",
    "hmmlearn>=0.3.3",
    "joblib>=1.5.1",
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
    "scikit-learn>=1.7.0",
    "ta>=0.11.0",
    "tqdm>=4.67.1",
]
